batch_size: 16
epoch: 30
learning_rate: 1e-4
gpu: 1
num_point: 256
optimizer: Adam
weight_decay: 1e-5
normal: True

defaults:
  - model: Hengshuang

hydra:
  run:
    dir: log/cls/${model.name}

  sweep:
    dir: log/cls
    subdir: ${model.name}